trigger:
  branches:
    include:
    - main

stages:
- stage: Build
  displayName: Build App
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestdJob
    displayName: Job de Test
    steps:
    - script: echo Building!
  - job: BuildJob
    displayName: Job de Build
    dependsOn: [TestdJob]
    steps:
    - checkout: self
