trigger:
  branches:
    include:
    - main

stages:
- stage: BuildPush
  jobs:
  - job: CheckoutRepo
    displayName: CheckoutRepo
    steps:
    - checkout: self
  - template: templates/build.yaml
    parameters:
      pool_name: 'ubuntu-latest'
      repo_name: $(Build.Repository.Name)
